// <auto-generated />
using System;
using Dsms.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dsms.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Dsms.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AuditQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("AuditRunId")
                        .HasColumnType("int");

                    b.Property<int>("ComplianceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionCategory")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("QuestionIsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionSortOrder")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuditQuestionId");

                    b.HasIndex("AuditRunId", "AuditQuestionId")
                        .IsUnique();

                    b.ToTable("AuditAnswers");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuditTemplateId");

                    b.ToTable("AuditQuestions");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("longtext");

                    b.Property<int>("AuditTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateTitleSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TemplateVersionSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuditTemplateId");

                    b.HasIndex("TenantId");

                    b.ToTable("AuditRuns");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("CommunityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("OriginalTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalTenantId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubmittedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("TemplateType")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("AuditTemplates");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.DataProtectionImpactAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NecessityAndProportionality")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextReviewAt")
                        .HasColumnType("date");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProtectiveMeasures")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForDpia")
                        .HasColumnType("text");

                    b.Property<int>("ResidualRisk")
                        .HasColumnType("int");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("ReviewedAt")
                        .HasColumnType("date");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RiskAssessment")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ProcessingActivityId");

                    b.ToTable("DataProtectionImpactAssessments", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EncryptedSmtpPassword")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Encryption")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SenderName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateKey")
                        .IsUnique();

                    b.ToTable("EmailTemplates", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.EvidenceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int?>("AuditRunId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DataProtectionImpactAssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MeasureId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessingActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UploadedByUserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.HasIndex("DataProtectionImpactAssessmentId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("ProcessingActivityId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("TenantId", "DataProtectionImpactAssessmentId");

                    b.HasIndex("TenantId", "ProcessingActivityId");

                    b.ToTable("EvidenceDocuments");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("longtext");

                    b.Property<int?>("AuditAnswerId")
                        .HasColumnType("int");

                    b.Property<int?>("AuditRunId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuditAnswerId");

                    b.HasIndex("AuditRunId");

                    b.HasIndex("TenantId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DataSubjectCategories")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("DpiaRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LegalBasis")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PersonalDataCategories")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Recipients")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleDepartment")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RetentionPeriod")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<bool>("ThirdCountryTransfer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ThirdCountryTransferDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ProcessingActivities", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityAuditAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditAnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditAnswerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProcessingActivityId", "AuditAnswerId")
                        .IsUnique();

                    b.ToTable("ProcessingActivityAuditAnswers", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasureId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProcessingActivityId", "MeasureId")
                        .IsUnique();

                    b.ToTable("ProcessingActivityMeasures", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("int");

                    b.Property<int>("RoleInProcessing")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ServiceProviderId", "ProcessingActivityId")
                        .IsUnique();

                    b.ToTable("ProcessingActivityServiceProviders", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityTom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProcessingActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingActivityId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TomId", "ProcessingActivityId")
                        .IsUnique();

                    b.ToTable("ProcessingActivityToms", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DataProcessingAgreementDate")
                        .HasColumnType("date");

                    b.Property<bool>("DataProcessingAgreementExists")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DataProcessingAgreementReviewResult")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DataProcessingAgreementReviewedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDataProcessor")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RiskAssessment")
                        .HasColumnType("int");

                    b.Property<string>("ServicePurpose")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("SubProcessorsAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SubProcessorsDescription")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("ThirdCountry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("ThirdCountryInvolvement")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ThirdCountryLegalBasis")
                        .HasColumnType("int");

                    b.Property<string>("ThirdCountryTransferGuarantees")
                        .HasColumnType("text");

                    b.Property<string>("TomsReviewResult")
                        .HasColumnType("text");

                    b.Property<bool>("TomsReviewed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("TomsReviewedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsDataProcessor");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ServiceProviderTom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("TomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TomId");

                    b.HasIndex("ServiceProviderId", "TomId")
                        .IsUnique();

                    b.ToTable("ServiceProviderToms", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionRequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletionRequestedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("DeletionScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeletionRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("LegalName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Tom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ArchivedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceReference")
                        .HasColumnType("text");

                    b.Property<int>("ImplementationStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("NextReviewAt")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProtectionGoal")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ImplementationStatus");

                    b.ToTable("Toms", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.UserTenant", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("UserTenants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditAnswer", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.AuditQuestion", "AuditQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("AuditQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("Answers")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditQuestion");

                    b.Navigation("AuditRun");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditQuestion", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.AuditTemplate", "AuditTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("AuditTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditTemplate");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditRun", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.AuditTemplate", "AuditTemplate")
                        .WithMany("AuditRuns")
                        .HasForeignKey("AuditTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AuditRuns")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditTemplate");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditTemplate", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AuditTemplates")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.DataProtectionImpactAssessment", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.ProcessingActivity", "ProcessingActivity")
                        .WithMany("DpiaAssessments")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("DpiaAssessments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingActivity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.EvidenceDocument", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("Documents")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.DataProtectionImpactAssessment", "DataProtectionImpactAssessment")
                        .WithMany("Documents")
                        .HasForeignKey("DataProtectionImpactAssessmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.Measure", "Measure")
                        .WithMany("Documents")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.ProcessingActivity", "ProcessingActivity")
                        .WithMany("Documents")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("Documents")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Documents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditRun");

                    b.Navigation("DataProtectionImpactAssessment");

                    b.Navigation("Measure");

                    b.Navigation("ProcessingActivity");

                    b.Navigation("ServiceProvider");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Measure", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.AuditAnswer", "AuditAnswer")
                        .WithMany("Measures")
                        .HasForeignKey("AuditAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("Measures")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Measures")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditAnswer");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivity", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ProcessingActivities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityAuditAnswer", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.AuditAnswer", "AuditAnswer")
                        .WithMany("ProcessingActivityLinks")
                        .HasForeignKey("AuditAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.ProcessingActivity", "ProcessingActivity")
                        .WithMany("AuditAnswerLinks")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditAnswer");

                    b.Navigation("ProcessingActivity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityMeasure", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.Measure", "Measure")
                        .WithMany("ProcessingActivityLinks")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.ProcessingActivity", "ProcessingActivity")
                        .WithMany("MeasureLinks")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measure");

                    b.Navigation("ProcessingActivity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityServiceProvider", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.ProcessingActivity", "ProcessingActivity")
                        .WithMany("ServiceProviderLinks")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("ProcessingActivityLinks")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessingActivity");

                    b.Navigation("ServiceProvider");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivityTom", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.ProcessingActivity", "ProcessingActivity")
                        .WithMany("TomLinks")
                        .HasForeignKey("ProcessingActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tom", "Tom")
                        .WithMany("ProcessingActivityLinks")
                        .HasForeignKey("TomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingActivity");

                    b.Navigation("Tenant");

                    b.Navigation("Tom");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ServiceProvider", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ServiceProviders")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ServiceProviderTom", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("TomLinks")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Domain.Entities.Tom", "Tom")
                        .WithMany("ServiceProviderLinks")
                        .HasForeignKey("TomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");

                    b.Navigation("Tenant");

                    b.Navigation("Tom");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Tom", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Toms")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.UserTenant", b =>
                {
                    b.HasOne("Dsms.Web.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Data.ApplicationUser", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dsms.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dsms.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dsms.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dsms.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dsms.Web.Data.ApplicationUser", b =>
                {
                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditAnswer", b =>
                {
                    b.Navigation("Measures");

                    b.Navigation("ProcessingActivityLinks");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditRun", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Documents");

                    b.Navigation("Measures");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.AuditTemplate", b =>
                {
                    b.Navigation("AuditRuns");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.DataProtectionImpactAssessment", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Measure", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ProcessingActivityLinks");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ProcessingActivity", b =>
                {
                    b.Navigation("AuditAnswerLinks");

                    b.Navigation("Documents");

                    b.Navigation("DpiaAssessments");

                    b.Navigation("MeasureLinks");

                    b.Navigation("ServiceProviderLinks");

                    b.Navigation("TomLinks");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.ServiceProvider", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ProcessingActivityLinks");

                    b.Navigation("TomLinks");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AuditRuns");

                    b.Navigation("AuditTemplates");

                    b.Navigation("Documents");

                    b.Navigation("DpiaAssessments");

                    b.Navigation("Measures");

                    b.Navigation("ProcessingActivities");

                    b.Navigation("ServiceProviders");

                    b.Navigation("Toms");

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("Dsms.Web.Domain.Entities.Tom", b =>
                {
                    b.Navigation("ProcessingActivityLinks");

                    b.Navigation("ServiceProviderLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
